version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=my_store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=miriamnavamucino@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=my_store
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    ports:
      - 8080:80